#!/bin/bash
#PBS -N vc_monolith
#PBS -q big_mem
#PBS -l walltime=6:00:00
#PBS -l nodes=2:ppn=2
#PBS -A aaa

export TURBINE_LOG=1
export ADLB_DEBUG_RANKS=1
export SWIFT_TMP=/ui/ncsa/jacobrh/res_vc_test/tmp
module load swift-t/swift-t-1.1

#/usr/local/mpi/mpich/mpich-3.1.4-intel-15.0.u3/bin/mpiexec /usr/local/apps/bioapps/tcl/tcl8.6.6/bin/tclsh8.6 /ui/ncsa/jacobrh/res_vc_test/compiled.tic -runfile=~/res_vc_test/test.runfile

swift-t -n 5 -I /ui/ncsa/jacobrh/Swift-T-Variant-Calling/src -r /ui/ncsa/jacobrh/Swift-T-Variant-Calling/src/bioapps /ui/ncsa/jacobrh/Swift-T-Variant-Calling/src/VariantCalling.swift -runfile=~/res_vc_test/test.runfile &> /ui/ncsa/jacobrh/res_vc_test/Monolith_pipelinerun.log
