#!/bin/bash
#PBS -N swift_variant_calling
#PBS -l nodes=1:ppn=2,walltime=20:00:00
#PBS -M mkendzi2@illinois.edu
#PBS -m bae
#PBS -S /bin/bash
#PBS -A aaa
#PBS -q big_mem


module load /usr/local/apps/bioapps/modules/swift-t/swift-t-1.1

export TURBINE_LOG=1

swift-t -O3 -o /projects/bioinformatics/HudsonSoybeanProject/swift_T_variant_calling_updated/config/test1_compiled_output_file.tic -I /projects/bioinformatics/HudsonSoybeanProject/swift_T_variant_calling_updated/Swift-T-Variant-Calling/src/ -r /projects/bioinformatics/HudsonSoybeanProject/swift_T_variant_calling_updated/Swift-T-Variant-Calling/src/bioapps -n 3 /projects/bioinformatics/HudsonSoybeanProject/swift_T_variant_calling_updated/Swift-T-Variant-Calling/src/VariantCalling.swift -runfile=/projects/bioinformatics/HudsonSoybeanProject/swift_T_variant_calling_updated/config/se_test.runfile &> /projects/bioinformatics/HudsonSoybeanProject/swift_T_variant_calling_updated/config/swift_variant_calling_test1.eo

