export PROCS=2 #total number of MPI processes
export PPN=3 #Number of processes per node 
export NODES=2
export QUEUE=normal
export WALLTIME=01:00:00
export TURBINE_LOG=1
export MAIL_ENABLED=1
export MAIL_ADDRESS=azzaea@gmail.com
#export ADLB_DEBUG_RANKS=1
export TURBINE_APP_RETRIES=10
export SWIFT_TMP=/home/groups/hpcbio_shared/azza/swift_T_project/results/synthetic_data/tmp_swift
